---
  - name: Install tools for remote access
    apt: name={{ item }} state=present
    with_items:
      - openssh-server

  - name: Check if ssh_login group exists
    group:
      name: "{{ secure_ssh_group }}"
      state: present
    register: logingroup
    check_mode: yes # do not create group

# At this point, at least one user must be present which is member
# of ssh_login, otherwise we will lock ourselves out of the system!
# If the group was just created, that means this is probably not the case.
  - fail:
      msg: "{{ secure_ssh_group }} must exist, you will lock yourself out of the system!"
    when: logingroup.changed

  - name: Secured ssh configuration (disallows password login!)
    template:
      src: "sshd_config.j2"
      dest: "/etc/ssh/sshd_config"
      owner: root
      group: root
      mode: 0644
      backup: yes
    notify:
      - restart ssh
