---
  - name: Install tools for remote access
    apt: name={{ item }} state=present
    with_items:
      - openssh-server

  - group:
      name: ssh_login
      state: present

  - name: Adding existing user to group ssh_login
    user: name=user
          groups=ssh_login
          append=yes


  - name: Make sure that the .ssh directory exsists
    file:
      path: "/home/user/.ssh"
      state: directory
      mode: 0755

  - name: Download authorized_keys file
    get_url:
      url: "{{ ssh_authorized_keys }}"
      dest: "/home/user/.ssh/authorized_keys"
      owner: user
      group: user
      mode: 0644

  - name: Secured ssh configuration (disallows password login)
    copy:
      src: "files/sshd_config"
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Setup alternate SSH port (if specified)
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^Port"
      line: "Port {{ secure_ssh_port }}"
    notify:
      - restart ssh
